---

project_name: zrun
before:
  hooks:
    - go mod tidy
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
#      - windows
#      - darwin
    goarch:
      - amd64
      - arm64
    id: "zrun"
    dir: .
    main: ./main.go
    ldflags:
      - -s -w -X github.com/zcubbs/zrun/internal/defaults.Version={{.Version}} -X github.com/zcubbs/zrun/internal/defaults.Commit={{.Commit}} -X github.com/zcubbs/zrun/internal/defaults.Date={{.Date}}

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^conf:'
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
signs:
  - cmd: gpg
    args:
      - --output
      - $signature
      - --detach-sig
      - $artifact
    signature: ${artifact}.sig
    artifacts: none
release:
  github:
    owner: zcubbs
    name: zrun
  draft: true
  prerelease: auto
  discussion_category_name: General
  header: |
    ## zrun ({{ .Date }})
    
    Welcome to this new release!
  footer: |
    ## Thanks!
    Those were the changes on {{ .Tag }}!
    Read more on our documentation page: https://github.com/zcubbs/zrun
  name_template: "{{.Tag}}"

