name: build-release
on: 
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '_assets/**'
      - '.gitignore'
jobs:
  dagger:
    name: dagger-pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3
      - run: go run ci/main.go
