name: dagger-pipeline

defaults:
  run:
    shell: bash
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
jobs:
  build-release:
    name: build-package-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: actions/checkout@v3
      - run: go run ci/main.go
