name: dagger-pipeline

defaults:
  run:
    shell: bash
on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '_assets/**'
      - '.gitignore'
jobs:
  build-release:
    name: build-package-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: actions/checkout@v3
      - run: go run ci/main.go
