name: release

defaults:
  run:
    shell: bash
on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
    paths-ignore:
      - 'README.md'
      - '_assets/**'
      - '.gitignore'
jobs:
  release:
    name: go-releaser
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: actions/checkout@v3
      - name: release
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release -f _goreleaser.yaml --rm-dist
        env:
          # Must setup a GITHUB_TOKEN secret with package write access
          GITHUB_TOKEN: ${{ secrets.GORELEASE_GITHUB_TOKEN }}



