name: lint

defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '_assets/**'
      - '.github/**'
      - 'scripts/**'
      - 'LICENSE'
      - 'Makefile'
      - '_goreleaser.yaml'
      - 'golangci.yaml'
      - '.dockerignore
      - '.gitignore'
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 5m



