name: release

defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
    paths-ignore:
      - 'README.md'
      - '_assets/**'
      - '.github/**'
      - 'scripts/**'
      - 'LICENSE'
      - 'Makefile'
      - '_goreleaser.yaml'
      - 'golangci.yaml'
      - '.dockerignore
      - '.gitignore'
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - uses: goreleaser/goreleaser-action@v4
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: latest
          args: release -f _goreleaser.yaml --clean
        env:
          # Must setup a GITHUB_TOKEN secret with package write access
          GITHUB_TOKEN: ${{ secrets.GORELEASE_GITHUB_TOKEN }}



