name: release

defaults:
  run:
    shell: bash
on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - uses: goreleaser/goreleaser-action@v4
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro':
          distribution: goreleaser
          version: latest
          args: release -f _goreleaser.yaml --clean
        env:
          # Must setup a GITHUB_TOKEN secret with package write access
          GITHUB_TOKEN: ${{ secrets.GORELEASE_GITHUB_TOKEN }}



